"""rename roles

Revision ID: 3734d8f06ee4
Revises: c8fd9ae80856
Create Date: 2021-05-07 16:08:41.902748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3734d8f06ee4'
down_revision = 'c8fd9ae80856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('moderator', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('reporter', sa.Boolean(), nullable=True))
    op.drop_column('users', 'is_reporter')
    op.drop_column('users', 'is_moderator')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_moderator', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_reporter', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'reporter')
    op.drop_column('users', 'moderator')
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###
