"""confirmed_application on listing

Revision ID: c66d96df3c1f
Revises: ac16b2f398a1
Create Date: 2021-05-21 00:26:10.789910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c66d96df3c1f'
down_revision = 'ac16b2f398a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('confirmed_application_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'listing', 'application', ['confirmed_application_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'listing', type_='foreignkey')
    op.drop_column('listing', 'confirmed_application_id')
    # ### end Alembic commands ###
