"""left review boolead modev from application to listing

Revision ID: c84559f2fd70
Revises: c66d96df3c1f
Create Date: 2021-05-22 14:45:45.404287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c84559f2fd70'
down_revision = 'c66d96df3c1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'applied_user_to_listing_author_left_rating')
    op.drop_column('application', 'listing_author_to_applied_user_left_rating')
    op.add_column('listing', sa.Column('author_left_review', sa.Boolean(), nullable=True))
    op.add_column('listing', sa.Column('walker_left_review', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'walker_left_review')
    op.drop_column('listing', 'author_left_review')
    op.add_column('application', sa.Column('listing_author_to_applied_user_left_rating', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('application', sa.Column('applied_user_to_listing_author_left_rating', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
