"""add user roles(admin, moderator, reporter), route permission wrapper

Revision ID: c8fd9ae80856
Revises: 748890b3ba8a
Create Date: 2021-05-07 15:21:48.518140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8fd9ae80856'
down_revision = '748890b3ba8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_moderator', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_reporter', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_reporter')
    op.drop_column('users', 'is_moderator')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
