"""listings update

Revision ID: ea946c378a51
Revises: 5582c5611f0b
Create Date: 2021-05-14 13:58:51.930405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea946c378a51'
down_revision = '5582c5611f0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('listing', sa.Column('location_text', sa.String(), nullable=True))
    op.add_column('listing', sa.Column('lon', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'lon')
    op.drop_column('listing', 'location_text')
    op.drop_column('listing', 'lat')
    # ### end Alembic commands ###
