"""listing application, rating

Revision ID: f671d532bcb7
Revises: ea946c378a51
Create Date: 2021-05-15 21:39:52.997934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f671d532bcb7'
down_revision = 'ea946c378a51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('user_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', postgresql.UUID(), nullable=False),
    sa.Column('applied_user_id', postgresql.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('listing_author_to_applied_user_left_rating', sa.Boolean(), nullable=True),
    sa.Column('applied_user_to_listing_author_left_rating', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['applied_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application')
    op.drop_table('ratings')
    # ### end Alembic commands ###
